// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Router$WhatsAppReason from "./Router.bs.js";
import * as Page_Home$WhatsAppReason from "../pages/Page_Home.bs.js";
import * as Page_NotFound$WhatsAppReason from "../pages/Page_NotFound.bs.js";

function Root(Props) {
  var route = Router$WhatsAppReason.useRouter(undefined);
  if (route !== undefined) {
    return React.createElement(Page_Home$WhatsAppReason.make, {});
  } else {
    return React.createElement(Page_NotFound$WhatsAppReason.make, {});
  }
}

var make = Root;

export {
  make ,
  
}
/* react Not a pure module */
