// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.bs.js";

function Create(Config) {
  var Router$Create = function (Props) {
    var children = Props.children;
    var match = React.useReducer((function (_state, action) {
            return {
                    route: action._0
                  };
          }), {
          route: Curry._1(Config.toRoute, ReasonReactRouter.dangerouslyGetInitialUrl(undefined))
        });
    var dispatch = match[1];
    React.useEffect((function () {
            var watcherID = ReasonReactRouter.watchUrl(function (url) {
                  return Curry._1(dispatch, /* UpdateRoute */{
                              _0: Curry._1(Config.toRoute, url)
                            });
                });
            return (function (param) {
                      return ReasonReactRouter.unwatchUrl(watcherID);
                    });
          }), []);
    return Curry._1(children, match[0].route);
  };
  return {
          make: Router$Create
        };
}

export {
  Create ,
  
}
/* react Not a pure module */
