// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Page_NotFound(Props) {
  return React.createElement("div", undefined, "Can't seem to find the page you're looking for :/");
}

var make = Page_NotFound;

export {
  make ,
  
}
/* react Not a pure module */
