// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Greet$WhatsAppReason from "./Greet.bs.js";

function Page_Home(Props) {
  return React.createElement(Greet$WhatsAppReason.make, {
              name: "Visitor"
            });
}

var make = Page_Home;

export {
  make ,
  
}
/* react Not a pure module */
