// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ApolloHooks from "reason-apollo-hooks/src/ApolloHooks.bs.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Queries$WhatsAppReason from "../graphql/Queries.bs.js";
import * as SignInForm$WhatsAppReason from "./SignInForm.bs.js";
import * as ChatsListScreen$WhatsAppReason from "./ChatsListScreen.bs.js";

function str(prim) {
  return prim;
}

function AuthService(Props) {
  var match = ApolloHooks.useQuery(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Queries$WhatsAppReason.MeQuery.definition);
  var simple = match[0];
  var tmp;
  if (typeof simple === "number") {
    tmp = simple === /* Loading */0 ? React.createElement("p", undefined, "Loading...") : React.createElement("p", undefined, "Error");
  } else if (simple.TAG) {
    tmp = React.createElement("p", undefined, "Error");
  } else {
    var value = simple._0.me;
    var me = value !== undefined ? Caml_option.valFromOption(value) : null;
    console.log("Me: ", me);
    var me2 = (me == null) ? undefined : Caml_option.some(me);
    console.log("Me2: ", me2);
    tmp = (me == null) ? React.createElement(SignInForm$WhatsAppReason.make, {}) : React.createElement(ChatsListScreen$WhatsAppReason.make, {
            me: me
          });
  }
  return React.createElement("div", undefined, tmp);
}

var make = AuthService;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
