// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as UserContext$WhatsAppReason from "../context/UserContext.bs.js";

var make = UserContext$WhatsAppReason.context.Provider;

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

export {
  make ,
  makeProps ,
  
}
/* make Not a pure module */
