// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Emotion from "@ahrefs/bs-emotion/src/Emotion.bs.js";

var styles = Emotion.css(undefined, /* :: */{
      _0: Emotion.height(Emotion.px(265)),
      _1: /* [] */0
    });

function make(props) {
  var stylesObject = {
    className: styles
  };
  var newProps = Object.assign(stylesObject, props);
  var chil = props.children;
  return React.createElement("div", newProps, [chil !== undefined ? chil : null]);
}

var Intro = {
  styles: styles,
  make: make
};

var styles$1 = Emotion.css(undefined, /* :: */{
      _0: Emotion.width(Emotion.px(125)),
      _1: /* :: */{
        _0: Emotion.height(Emotion.auto),
        _1: /* :: */{
          _0: Emotion.marginLeft(Emotion.auto),
          _1: /* :: */{
            _0: Emotion.marginRight(Emotion.auto),
            _1: /* :: */{
              _0: Emotion.paddingTop(Emotion.px(70)),
              _1: /* :: */{
                _0: Emotion.display(/* block */888960333),
                _1: /* [] */0
              }
            }
          }
        }
      }
    });

function make$1(props) {
  var stylesObject = {
    className: styles$1
  };
  var newProps = Object.assign(stylesObject, props);
  var chil = props.children;
  return React.createElement("img", newProps, [chil !== undefined ? chil : null]);
}

var Icon = {
  styles: styles$1,
  make: make$1
};

var styles$2 = Emotion.css(undefined, /* :: */{
      _0: Emotion.width(Emotion.pct(100)),
      _1: /* :: */{
        _0: Emotion.textAlign(Emotion.center),
        _1: /* :: */{
          _0: Emotion.color(Emotion.Css.Color.white),
          _1: /* [] */0
        }
      }
    });

function make$2(props) {
  var stylesObject = {
    className: styles$2
  };
  var newProps = Object.assign(stylesObject, props);
  var chil = props.children;
  return React.createElement("h2", newProps, [chil !== undefined ? chil : null]);
}

var Title = {
  styles: styles$2,
  make: make$2
};

var styles$3 = Emotion.css(undefined, /* :: */{
      _0: Emotion.position(Emotion.fixed),
      _1: /* :: */{
        _0: Emotion.bottom(Emotion.px(10)),
        _1: /* :: */{
          _0: Emotion.left(Emotion.px(10)),
          _1: /* :: */{
            _0: Emotion.select("label", /* :: */{
                  _0: Emotion.color(Emotion.hex("4299e1")),
                  _1: /* [] */0
                }),
            _1: /* [] */0
          }
        }
      }
    });

function make$3(props) {
  var stylesObject = {
    className: styles$3
  };
  var newProps = Object.assign(stylesObject, props);
  var chil = props.children;
  return React.createElement("div", newProps, [chil !== undefined ? chil : null]);
}

var Alternative = {
  styles: styles$3,
  make: make$3
};

export {
  Intro ,
  Icon ,
  Title ,
  Alternative ,
  
}
/* styles Not a pure module */
