// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Chakra__Alert from "bs-chakra/src/Chakra__Alert.bs.js";
import * as Core from "@chakra-ui/core";

function ErrorAlert(Props) {
  var message = Props.message;
  return React.createElement("div", {
              style: {
                marginTop: "20px",
                width: "100%"
              }
            }, React.createElement(Core.Alert, Chakra__Alert.makeProps(/* error */-215364664, undefined, undefined, undefined, undefined, undefined, null)(undefined, undefined), React.createElement(Core.AlertIcon, {}), message));
}

var make = ErrorAlert;

export {
  make ,
  
}
/* react Not a pure module */
