// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Emotion from "@ahrefs/bs-emotion/src/Emotion.bs.js";

var styles = Emotion.css(undefined, /* :: */{
      _0: Emotion.textAlign(Emotion.center),
      _1: /* :: */{
        _0: Emotion.marginTop(Emotion.rem(3)),
        _1: /* [] */0
      }
    });

function make(props) {
  var stylesObject = {
    className: styles
  };
  var newProps = Object.assign(stylesObject, props);
  var chil = props.children;
  return React.createElement("div", newProps, [chil !== undefined ? chil : null]);
}

var Container = {
  styles: styles,
  make: make
};

var styles$1 = Emotion.css(undefined, /* :: */{
      _0: Emotion.fontSize(Emotion.rem(1.875)),
      _1: /* :: */{
        _0: Emotion.textDecoration(Emotion.none),
        _1: /* :: */{
          _0: Emotion.color(Emotion.hex("4299e1")),
          _1: /* [] */0
        }
      }
    });

function make$1(props) {
  var stylesObject = {
    className: styles$1
  };
  var newProps = Object.assign(stylesObject, props);
  var chil = props.children;
  return React.createElement("div", newProps, [chil !== undefined ? chil : null]);
}

var $$Text = {
  styles: styles$1,
  make: make$1
};

var styles$2 = Emotion.css(undefined, /* :: */{
      _0: Emotion.fontSize(Emotion.rem(1.875)),
      _1: /* :: */{
        _0: Emotion.color(Emotion.hex("1a202c")),
        _1: /* :: */{
          _0: Emotion.marginBottom(Emotion.rem(1)),
          _1: /* [] */0
        }
      }
    });

function make$2(props) {
  var stylesObject = {
    className: styles$2
  };
  var newProps = Object.assign(stylesObject, props);
  var chil = props.children;
  return React.createElement("a", newProps, [chil !== undefined ? chil : null]);
}

var Link = {
  styles: styles$2,
  make: make$2
};

function SignUpForm(Props) {
  return React.createElement(make, {
              children: null
            }, React.createElement(make$1, {
                  children: null
                }, "👋 SignUpForm Placeholder ", React.createElement("code", undefined, "src/components/SignUpForm.re")), React.createElement("span", {
                  className: Emotion.css(undefined, /* :: */{
                        _0: Emotion.display(/* flex */-1010954439),
                        _1: /* [] */0
                      })
                }));
}

var make$3 = SignUpForm;

export {
  Container ,
  $$Text ,
  Link ,
  make$3 as make,
  
}
/* styles Not a pure module */
