// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

var initialState = {
  username: "",
  email: "",
  password: ""
};

function reducer(state, action) {
  if (typeof action === "number") {
    return initialState;
  }
  switch (action.TAG | 0) {
    case /* SetUsername */0 :
        return {
                username: action._0,
                email: state.email,
                password: state.password
              };
    case /* SetEmail */1 :
        return {
                username: state.username,
                email: action._0,
                password: state.password
              };
    case /* SetPassword */2 :
        return {
                username: state.username,
                email: state.email,
                password: action._0
              };
    
  }
}

function valueFromEvent(evt) {
  return evt.target.value;
}

function useForm(callback) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var handleChange = function (evt) {
    evt.persist();
    var match = evt.target.name;
    switch (match) {
      case "email" :
          return Curry._1(dispatch, {
                      TAG: /* SetEmail */1,
                      _0: evt.target.value
                    });
      case "password" :
          return Curry._1(dispatch, {
                      TAG: /* SetPassword */2,
                      _0: evt.target.value
                    });
      case "username" :
          return Curry._1(dispatch, {
                      TAG: /* SetUsername */0,
                      _0: evt.target.value
                    });
      default:
        return ;
    }
  };
  var handleSubmit = function (evt) {
    evt.preventDefault();
    Curry._1(callback, undefined);
    return Curry._1(dispatch, /* ResetState */0);
  };
  return [
          match[0],
          handleChange,
          handleSubmit
        ];
}

function SimpleForm(Props) {
  var logger = function (param) {
    console.log("Form submitted");
    
  };
  var match = useForm(logger);
  var handleChange = match[1];
  var state = match[0];
  return React.createElement("div", {
              className: "section is-fullheight"
            }, React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "column is-4 is-offset-4"
                    }, React.createElement("div", {
                          className: "box"
                        }, React.createElement("form", {
                              onSubmit: match[2]
                            }, React.createElement("div", {
                                  className: "field"
                                }, React.createElement("label", {
                                      className: "label"
                                    }, "Email Address"), React.createElement("div", {
                                      className: "control"
                                    }, React.createElement("input", {
                                          className: "input",
                                          name: "email",
                                          required: true,
                                          type: "email",
                                          value: state.email,
                                          onChange: handleChange
                                        }))), React.createElement("div", {
                                  className: "field"
                                }, React.createElement("label", {
                                      className: "label"
                                    }, "Password"), React.createElement("div", {
                                      className: "control"
                                    }, React.createElement("input", {
                                          className: "input",
                                          name: "password",
                                          required: true,
                                          type: "password",
                                          value: state.password,
                                          onChange: handleChange
                                        }))), React.createElement("button", {
                                  className: "button is-block is-info is-fullwidth",
                                  type: "submit"
                                }, "Login"))))));
}

var make = SimpleForm;

export {
  initialState ,
  reducer ,
  valueFromEvent ,
  useForm ,
  make ,
  
}
/* react Not a pure module */
