// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$String from "bs-platform/lib/es6/string.js";

function createCookie(name, value, days, param) {
  if (days !== undefined) {
    var date = new Date();
    var offset = date.getTime() + Math.imul(Math.imul(Math.imul(Math.imul(days, 24), 60), 60), 1000);
    date.setTime(offset);
    var expires = date.toUTCString();
    document.cookie = name + ("=" + (value + ("; expires" + (expires + "; path=/"))));
    return ;
  }
  document.cookie = name + ("=" + (value + "; path=/"));
  
}

function readCookie(name) {
  var nameEQ = name + "=";
  var cookieChunks = document.cookie.split(";").map($$String.trim);
  var cookie = cookieChunks.find(function (s) {
        return s.startsWith(nameEQ);
      });
  if (cookie !== undefined) {
    return cookie.substring(nameEQ.length);
  }
  
}

function eraseCookie(name) {
  return createCookie(name, "", -1, undefined);
}

function loggedIn(param) {
  var token = readCookie("access_token");
  if (token !== undefined) {
    return token.length > 0;
  } else {
    return false;
  }
}

function logOut(setWarningOpt, param) {
  var setWarning = setWarningOpt !== undefined ? setWarningOpt : false;
  if (setWarning) {
    localStorage.setItem("loginFlash", "Your login has expired or is invalid.");
  }
  return eraseCookie("access_token");
}

export {
  createCookie ,
  readCookie ,
  eraseCookie ,
  loggedIn ,
  logOut ,
  
}
/* No side effect */
