// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function nonEmptyString(value) {
  return value !== "";
}

function validEUsername(str) {
  var __x = new RegExp("^[^@\\s\\:]+@employmenthero\\.com$");
  var param = __x.exec(str);
  return param !== null;
}

export {
  nonEmptyString ,
  validEUsername ,
  
}
/* No side effect */
