// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";

var tokenKey = "__TOKEN__";

var userIdKey = "__USER_ID__";

function setSessionToStorage(session) {
  localStorage.setItem(tokenKey, session.token);
  localStorage.setItem(userIdKey, session.userId);
  
}

function getSessionFromStorage(param) {
  var token = localStorage.getItem(tokenKey);
  var userId = localStorage.getItem(userIdKey);
  if (!(token == null) && !(userId == null)) {
    return /* Valid */{
            _0: {
              token: token,
              userId: userId
            }
          };
  } else {
    return /* Invalid */0;
  }
}

function clearSession(param) {
  List.map((function (prim) {
          localStorage.removeItem(prim);
          
        }), /* :: */{
        _0: tokenKey,
        _1: /* :: */{
          _0: userIdKey,
          _1: /* [] */0
        }
      });
  
}

export {
  tokenKey ,
  userIdKey ,
  setSessionToStorage ,
  getSessionFromStorage ,
  clearSession ,
  
}
/* No side effect */
