// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

var graphEndpoint = process.env.GRAPHQL_ENDPOINT;

function str(prim) {
  return prim;
}

function toOption(value) {
  return Caml_option.some(value);
}

function optionToString(x) {
  if (x !== undefined) {
    return x;
  } else {
    return "";
  }
}

var graphEndpoint$1 = (graphEndpoint == null) ? undefined : Caml_option.some(graphEndpoint);

export {
  graphEndpoint$1 as graphEndpoint,
  str ,
  toOption ,
  optionToString ,
  
}
/* graphEndpoint Not a pure module */
