// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

var initValue = {
  me: /* Loading */1
};

var context = React.createContext(initValue);

function useMe(param) {
  return React.useContext(context);
}

var make = context.Provider;

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var ContextProvider = {
  make: make,
  makeProps: makeProps
};

export {
  initValue ,
  context ,
  useMe ,
  ContextProvider ,
  
}
/* context Not a pure module */
